version: '3.4'

services:
  benchmarks:
    build:
      context: .
      dockerfile: Docker/Dockerfile.benchmarks
    image: quiver:benchmarks
    working_dir: /app
    volumes:
      - ./submodules/quiver-data:/app/submodules/quiver-data
      - ./submodules/oton:/app/submodules/oton
      - ./models:/usr/local/share/ocrd-resources/
      - ./data:/app/data
      - ./workflows:/app/workflows