version: '3.4'

name: quiver

services:
  ocr:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    #environment:
    #  - RELEASE_TAG=${RELEASE_TAG}
    volumes:
      - ./gt:/app/gt
      - ./workflows:/app/workflows
      # mount your modules, custom workflows and data here
      - ./models/ocrd-tesserocr-recognize:/usr/local/share/tessdata/
      - ./models/ocrd-calamari-recognize:/usr/local/share/ocrd-resources/
      - ./logs:/app/logs
      - ./src:/app/src