version: '3.4'

services:
  benchmarks:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./models:/usr/local/share/ocrd-resources/
      - ./data:/app/data
      - ./workflows:/app/workflows